name: pull request ci
on:
  pull_request:

jobs:
  pull-request-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          # important to set a fetch depth of 2. By default the checkout action make no history available
          fetch-depth: 2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: run pitest
        # pitest has been bound to a profile called pitest for normal running
        # we add config to analyse only changes made within a PR and treat surviving mutants as check errors
        # failWhenNoMutations is unset in the pom, as otherwise PRs that do not affect java code would fail
        run: mvn -e -B -Ppitest -Dfeatures="+GIT(from[HEAD~1]), +github(level[error])" test
      - name: update pull request
        run: mvn -e -B -DrepoToken=${{ secrets.GITHUB_TOKEN }} pitest-github:github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}